name: Workflow Rafa Ferri
on:
  push:
    branches:
      - main
jobs:
  linter-execution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint